# Generated by Django 2.0.6 on 2018-06-30 13:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import students.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('male', 'Мужской'), ('female', 'Женский'), ('none', 'Не указано')], default='none', max_length=6)),
                ('location', models.CharField(blank=True, max_length=30)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('avatar', models.ImageField(upload_to=students.models.get_filename_avatar_student)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='profilestudent',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='profilestudent',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='profilestudent',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='profilestudent',
            name='location',
        ),
    ]
