# Generated by Django 2.0.6 on 2018-07-01 12:44

from django.db import migrations, models
import students.models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20180630_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=students.models.get_filename_avatar_student),
        ),
    ]
