# Generated by Django 2.0.6 on 2018-09-18 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_courseuser_taskcourseuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseuser',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
