export const SHOW_SIGN_FORM_ACTION = {type: 'SHOW_SIGN_FORM'};
export const HIDE_SIGN_FORM_ACTION = { type: 'HIDE_SIGN_FORM'};
export const SHOW_REGISTER_CONTENT_ACTION = {type: 'SHOW_REGISTER_CONTENT_IN_SIGN_FORM'};
export const SHOW_LOGIN_CONTENT_ACTION = {type: 'SHOW_LOGIN_CONTENT_IN_SIGN_FORM'};
