# Generated by Django 2.0.6 on 2018-07-01 17:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(0, 5400)),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='date_begin',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
