# Generated by Django 2.0.6 on 2018-07-01 17:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20180701_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='code_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='cost_full',
            field=models.IntegerField(default=50000),
        ),
        migrations.AddField(
            model_name='course',
            name='cost_month',
            field=models.IntegerField(default=11500),
        ),
        migrations.AddField(
            model_name='course',
            name='demands',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
