# Generated by Django 2.0.6 on 2018-07-01 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_name', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('demands', models.TextField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='code_name',
        ),
        migrations.RemoveField(
            model_name='course',
            name='demands',
        ),
        migrations.RemoveField(
            model_name='course',
            name='description',
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AddField(
            model_name='course',
            name='course_description',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='courses.CourseDescription'),
            preserve_default=False,
        ),
    ]
