# Generated by Django 2.0.6 on 2018-07-01 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20180701_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='coursedescription',
            name='code_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
