# Generated by Django 2.0.6 on 2018-07-14 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20180712_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_description',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.CourseDescription', to_field='code_name'),
        ),
    ]
