# Generated by Django 2.0.6 on 2018-09-18 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_auto_20180918_1054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskuser',
            name='task',
        ),
        migrations.RemoveField(
            model_name='taskuser',
            name='user',
        ),
        migrations.DeleteModel(
            name='TaskUser',
        ),
    ]
